version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
  orgtool:
    # image: orgtool/orgtool
    image: orgtool
    ports:
      - "4000:4000"
    environment:
        PORT: 4000
        EXT_HOST: localhost
        EXT_PORT: 4000
        SECRET_KEY_BASE: put_your_own_secret_here_which_needs_to_be_at_least_sixtyfour_bytes
        TIMEOUT: 10 # timeout for start, important when starting orgtool and db at the same time
        # GOOGLE_CLIENT_ID: ...
        # GOOGLE_CLIENT_SECRET: ...
        # GOOGLE_REDIRECT_URI: ...
        # TWITTER_CLIENT_ID: ...
        # TWITTER_CLIENT_SECRET: ...
        # SLACK_CLIENT_ID: ...
        # SLACK_CLIENT_SECRET: ...
        # FACEBOOK_CLIENT_ID: ...
        # FACEBOOK_CLIENT_SECRET: ...
        # GITHUB_CLIENT_ID: ...
        # GITHUB_CLIENT_SECRET: ...
        # MICROSOFT_CLIENT_ID: ...
        # MICROSOFT_CLIENT_SECRET: ...
        # DISCORD_CLIENT_ID: ...
        # DISCORD_CLIENT_SECRET: ...
        # WORDPRESS_CLIENT_ID: ...
        # WORDPRESS_CLIENT_SECRET: ...
        # WORDPRESS_HOST: ...
    depends_on:
      - db
