version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
  orgtool:
    image: orgtool/orgtool
    ports:
      - "4000:4000"
    environment:
        PORT: 4000
        EXT_HOST: ${HOSTNAME}
        EXT_PORT: 4000
        SECRET_KEY_BASE: put_your_own_secret_here_which_needs_to_be_at_least_sixtyfour_bytes
        # GOOGLE_CLIENT_ID: ...
        # GOOGLE_CLIENT_SECRET: ...
        # GOOGLE_REDIRECT_URI: ...
    depends_on:
      - db