version: '2'
services:
  db:
    image: postgres
  orgtool:
    image: orgtool
    ports:
      - "4000:4000"
    environment:
        PORT: 4000
        EXT_HOST: ${HOSTNAME}
        EXT_PORT: 4000
        SECRET_KEY_BASE: put_your_own_secret_here
    depends_on:
      - db
